from .schedule_serializer import ScheduleSerializer
from .doctor_phone_serializer import DoctorPhoneSerializer
from .consultation_detail_serializer import ConsultationDetailSerializer
from .doctor_serializer import DoctorSerializer