services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: necktie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-hm(!z=c$mt1&p08pt6cc!pg=b2g*65pq!iwppiciw))^&=fqsa
      - DATABASE_URL=postgres://postgres:postgres@db:5432/necktie_db
    depends_on:
      - db

volumes:
  postgres_data:
