# Generated by Django 5.0.6 on 2024-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='phone',
        ),
    ]
