# Generated by Django 5.0.6 on 2024-06-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_clinic_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='area',
            new_name='district',
        ),
    ]
