# Generated by Django 5.0.6 on 2024-06-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationDetails',
            new_name='ConsultationDetail',
        ),
    ]
