# Generated by Django 5.0.6 on 2024-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_consultationdetails_consultationdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consultation_details',
            new_name='consultation_detail',
        ),
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('cantonese', 'Cantonese'), ('mandarin', 'Mandarin')], default='english', max_length=100),
        ),
    ]
