# Generated by Django 5.0.6 on 2024-06-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='service',
            new_name='speciality',
        ),
    ]
