# Generated by Django 5.0.6 on 2024-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_rename_service_doctor_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdetail',
            name='inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
