# Generated by Django 5.0.6 on 2024-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_consultationdetail_inclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdetail',
            name='member_exclusive_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
