# Generated by Django 5.0.6 on 2024-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_doctorphone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorphone',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
